<?php
$pageNames = array(
    'index.php' => 'SĀKUMS',
    'about_me.php' => 'PERSONĪGĀ INFORMĀCIJA',
    'agreement.php' => 'PIEKRIŠANA',
    'collectives.php' => 'KOLEKTĪVI',
    'participants.php' => 'DALĪBNIEKI',
    'editParticipant.php' => 'DALĪBNIEKA DATU REDIĢĒŠANA',
    'addParticipant.php' => 'DALĪBNIEKA PIEVIENOŠANA',
    'addCollective.php' => 'KOLEKTĪVA PIEVIENOŠANA',
    'editCollective.php' => 'KOLEKTĪVA DATU REDIĢĒŠANA',
    'categories.php' => 'KATEGORIJAS',
    'addCategory.php' => 'KATEGORIJAS PIEVIENOŠANA',
    'editCategory.php' => 'KATEGORIJAS DATU REDIĢĒŠANA',
    'participCollectives.php' => 'DALĪBNIEKI KOLEKTĪVOS',
    'addParticipCollective.php' => 'DALĪBNIEKA PIEVIENOŠANA KOLEKTĪVAM',
    'editParticipCollective.php' => 'DALĪBNIEKA SAISTĪJUMA REDIĢĒŠANA KOLEKTĪVĀ',
    'dances.php' => 'DEJAS',
    'addDance.php' => 'DEJAS PIEVIENOŠANA',
    'editDance.php' => 'DEJAS DATU REDIĢĒŠANA',
    'rehearsals.php' => 'MĒĢINĀJUMI',
    'addRehearsal.php' => 'MĒĢINĀJUMA PIEVIENOŠANA',
    'editRehearsal.php' => 'MĒĢINĀJUMA DATU REDIĢĒŠANA',
    'collectivesRehearsals.php' => 'MĒĢINĀJUMU SAISTĪJUMS AR KOLEKTĪVU KATEGORIJĀM',
    'addCollectivesRehearsals.php' => 'MĒĢINĀJUMA PIEVIENOŠANA KOLEKTĪVAM KATEGORIJĀ',
    'editCollectivesRehearsals.php' => 'MĒĢINĀJUMA SAISTĪJUMA REDIĢĒŠANA KOLEKTĪVĀ KATEGORIJĀ',
);